apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gradual-stoat-python 
  janus-idp.io/tekton: gradual-stoat-python
  backstage.io/kubernetes-id: gradual-stoat-python
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: gradual-stoat-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  